dist: trusty

language: elixir

matrix:
  include:
    - elixir: 1.10.1
      otp_release:
      - 21.1
      - 22

cache:
  directories:
    - deps
    - _build

script:
  - mix format --check-formatted --dry-run;
  - MIX_ENV=test mix do deps.get, deps.compile, coveralls.travis
