dist: trusty

language: elixir

matrix:
  include:
    - elixir: 1.11.2
      otp_release: 23.2
    - elixir: 1.11.2
      otp_release: 22.3
    - elixir: 1.11.2
      otp_release: 21.3
    - elixir: 1.10.4
      otp_release: 23.2
    - elixir: 1.10.4
      otp_release: 22.3
    - elixir: 1.10.4
      otp_release: 21.3

cache:
  directories:
    - deps
    - _build

script:
  - mix format --check-formatted --dry-run;
  - MIX_ENV=test mix do credo --strict, mix dialyzer
  - MIX_ENV=test mix do deps.get, deps.compile, coveralls.travis
